# DataSource Configuration
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/orcl
    username: sys as sysdba
    password: sysdba
    driver-class-name: oracle.jdbc.OracleDriver
server:
  port: 8081

